name: whisper_ggml_plus
description: Whisper.cpp Flutter plugin with Large-v3-Turbo (128-mel) support.
version: 1.3.0
repository: https://github.com/DDULDDUCK/whisper_ggml_plus

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  ffi: ^2.1.5
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0
  plugin_platform_interface: ^2.1.8
  universal_io: ^2.3.1
  flutter_riverpod: '>=2.6.1 <4.0.0'
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.4.15
  ffigen: ^20.1.1
  freezed: ^3.0.6
  json_serializable: ^6.12.0
  very_good_analysis: ^10.0.0

topics:
  - 'ggml'
  - 'artificial-intelligence'
  - 'machine-learning'

flutter:
  uses-material-design: true
  assets:
    - assets/models/ggml-silero-v6.2.0.bin
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true